import { PostType } from '../../components/Community/Post';

export const dummyPost: PostType[] = [
  {
    id: 1,
    match_date: '2024.01.01',
    home_team_name: 'kia',
    away_team_name: 'samsung',
    review_short: '재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 1,
    likes: 0,
    comments: 1,
    result: 'kia',
    stadium: 'kia경기장',
    weather: '맑음',
    photo: 11,
  },
  {
    id: 2,
    match_date: '2024.01.02',
    home_team_name: 'lg',
    away_team_name: 'doosan',
    review_short: '재미있었다 재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 2,
    likes: 1,
    comments: 2,
    result: 'lg',
    stadium: 'lg경기장',
    weather: '흐림',
    photo: 12,
  },
  {
    id: 3,
    match_date: '2024.01.03',
    home_team_name: 'ssg',
    away_team_name: 'kt',
    review_short: '재미있었다 재미있었다 재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 3,
    likes: 20,
    comments: 3,
    result: 'ssg',
    stadium: 'ssg경기장',
    weather: '비',
    photo: 13,
  },
  {
    id: 4,
    match_date: '2024.01.04',
    home_team_name: 'nc',
    away_team_name: 'hanhwa',
    review_short: '재미있었다 재미있었다 재미있었다 재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 1,
    likes: 300,
    comments: 4,
    result: 'nc',
    stadium: 'nc경기장',
    weather: '맑음',
    photo: 14,
  },
  {
    id: 5,
    match_date: '2024.01.05',
    home_team_name: 'lotte',
    away_team_name: 'kiwoom',
    review_short: '재미있었다재미있었다재미있었다재미있었다재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 2,
    likes: 4000,
    comments: 5,
    result: 'lotte',
    stadium: 'lotte경기장',
    weather: '맑음',
    photo: 15,
  },
  {
    id: 6,
    match_date: '2024.01.11',
    home_team_name: 'samsung',
    away_team_name: 'kia',
    review_short: '재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 3,
    likes: 1,
    comments: 0,
    result: 'samsung',
    stadium: 'samsung경기장',
    weather: '맑음',
    photo: 16,
  },
  {
    id: 7,
    match_date: '2024.01.12',
    home_team_name: 'doosan',
    away_team_name: 'lg',
    review_short: '재미있었다 재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 1,
    likes: 2,
    comments: 1,
    result: 'doosan',
    stadium: 'doosan경기장',
    weather: '맑음',
    photo: 17,
  },
  {
    id: 8,
    match_date: '2024.01.13',
    home_team_name: 'kt',
    away_team_name: 'ssg',
    review_short: '재미있었다 재미있었다 재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 2,
    likes: 3,
    comments: 20,
    result: 'kt',
    stadium: 'kt경기장',
    weather: '맑음',
    photo: 18,
  },
  {
    id: 9,
    match_date: '2024.01.14',
    home_team_name: 'hanhwa',
    away_team_name: 'nc',
    review_short: '재미있었다 재미있었다 재미있었다 재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 3,
    likes: 4,
    comments: 300,
    result: 'hanhwa',
    stadium: 'hanhwa경기장',
    weather: '맑음',
    photo: 19,
  },
  {
    id: 10,
    match_date: '2024.01.15',
    home_team_name: 'kiwoom',
    away_team_name: 'lotte',
    review_short: '재미있었다 재미있었다 재미있었다 재미있었다 재미있었다',
    review_long:
      '정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 정말 재미있었다 ',
    user_id: 1,
    likes: 5,
    comments: 4000,
    result: 'kiwoom',
    stadium: 'kiwoom경기장',
    weather: '맑음',
    photo: 20,
  },
];
