export const ROUTES = {
  HOME: '/',
  ARCHIVE_DETAIL: '/archive/:id',
  ADD_ARCHIVE: '/archive/add',
  POSTS: '/posts',
  ADD_POST: '/posts/add',
  POST_DETAIL: '/posts/:id',
  LEAGUE: '/league',
  SCHEDULE: 'schedule',
  STANDINGS: 'standings',
  LOGIN: '/users/login',
  JOIN: '/users/join',
  USER: '/users/user',
  RESET: '/users/reset',
};
